server:
  port: 8080
spring:
  application:
    name: ${env.appName}
  messages:
    basename: i18n
    encoding: UTF-8
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data.db?date_string_format=yyyy-MM-dd HH:mm:ss
  jpa:
    database-platform: top.werls.novel.common.utils.SQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    open-in-view: false
logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: classpath:/
    name: log
  charset:
    file: UTF-8
env:
  appName: 'novel'
  version: '0.0.1'
  isEnableSwagger: true
  jwt:
    expire: 30
    tokenHeader: Authorization
    tokenPrefix: 'Bearer'
    privateKey: classpath:private.pem
    publicKey: classpath:public.pem
